log: error
logger: file
warnings: 0
show_errors: 0
route_cache: 1
template_debug: 0

## Uncomment these lines to activate CAS authentication
#auth_sso:
#  - path: "/auth/cas"
#    class: "auth-sso-cas"
#    i18n: "auth_sso.cas.label"
#    package: "CAS"
#    options:
#      cas_url: "https://localhost:8443/cas"
#      authorization_path: "/authorize/sso"
#
#authorization_sso:
#  - path: "/authorize/sso"
#    package: "Simple"
