# LibreCat::Worker specific configuration options
_prefix:
  worker:

# Log directory for worker and supervisor log files
logdir: logs

## Uncomment when you want to register your publications with a DOI at DataCite
## See https://github.com/LibreCat/LibreCat/wiki/DOI-Registration for more information
# Datacite:
#   user: 'DEMO.XXX'
#   password: 'secret'

# FileUploader options are defined in files.yml
# ImageResizer options are defined in files.yml

Mailer:
  default_from: 'unknown@librecat.org'
